### ISSUE TITLE
Repo not in the npm registry

### ISSUE THREAD

**Issue by UnicornDeluxe** [visjs/vis-charts#3]
> npm ERR! 404  'vis-charts@latest' is not in the npm registry.

node version: v10.16.0
npm version: 6.9.0

full output:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vis-charts - Not found
npm ERR! 404
npm ERR! 404  'vis-charts@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-07-16T08_33_53_221Z-debug.log
```

**Comment by mojoaxel** [comment]
Thanks for the report. This repository is not yet published.

@Thomaash What do you think? Should we publish it like it is at the moment? Maybe as a beta release or something?

**Comment by Thomaash** [comment]
Does it work? The last time I tried it most examples failed and I had to rewrite some code to get at least a part of them working.

**Comment by Thomaash** [comment]
It doesn't even build. We'll have to ditch Uglify.js as it doesn't understand anything above ES5 but we are distributing ES2015 modules now.

**Comment by UnicornDeluxe** [comment]
> 
> 
> It doesn't even build. We'll have to ditch Uglify.js as it doesn't understand anything above ES5 but we are distributing ES2015 modules now.

I also tried building it myself and came across the same problem as you @Thomaash .

However for me the postinstall script didnt work either. Heres a fix: https://github.com/react-native-training/react-native-elements/commit/e009574b99406642c451b0bc2f665f612d03f6fb

**Comment by UnicornDeluxe** [comment]
> 
> 
> Thanks for the report. This repository is not yet published.
> 
> @Thomaash What do you think? Should we publish it like it is at the moment? Maybe as a beta release or something?

I would suggest updating the readme then, so people dont get confused.
As it currently states that it can be install via `npm install vis-charts`
